// Touken Ranbu-first English fallback dictionary.
// We keep this lightweight on purpose so we can expand it as more series are translated.

export const EN_EXACT_TERM_MAP: Record<string, string> = {
  // Companies / orgs
  ネルケプランニング: "Nelke Planning",
  マーベラス: "Marvelous",
  ニトロプラス: "Nitroplus",
  "DMM GAMES": "DMM GAMES",
  "ユークリッド・エージェンシー": "Euclid Agency",

  // Common labels / concepts
  刀剣乱舞: "Touken Ranbu",
  刀ステ: "Touken Ranbu: The Stage",
  刀ミュ: "Touken Ranbu: The Musical",
  真剣乱舞祭: "Shinken Ranbu Festival",
  単独行: "Solo Performance",
  日替わり出演: "Rotating appearance",
  会場替わり出演: "Venue-specific appearance",
  のみ出演: "Appears only in selected performances",
  複数役: "Multiple roles",
  再登場: "Returning appearance",
  刀剣男士: "Touken Danshi",
  審神者: "Saniwa",
  本丸: "Honmaru",
  時間遡行軍: "History Retrograde Army",
  歴史修正主義者: "Historical Revisionists",
  検非違使: "Kebiishi",
  歴史上人物: "Historical Figures",
  その他: "Others",
  新選組: "Shinsengumi",
  真田十勇士: "Sanada Ten Braves",
  源氏: "Minamoto Clan",
  平氏: "Taira Clan",
  奥州藤原氏: "Oshu Fujiwara Clan",
  織田軍: "Oda Army",
  伊達軍: "Date Army",
  幕府軍: "Shogunate Army",
  新政府軍: "New Government Army",
  講談師: "Storyteller",
  源氏物語: "The Tale of Genji",
  アンサンブル: "Ensemble",
  ダンサー: "Dancers",
  映像出演: "Video Appearance",
  声の出演: "Voice Appearance",
  原案: "Original Work",
  脚本: "Script",
  演出: "Direction",
  振付: "Choreography",
  音楽監督: "Music Direction",
  主催: "Organizer",

  // Sword warriors / role names
  加州清光: "Kashu Kiyomitsu",
  三日月宗近: "Mikazuki Munechika",
  大和守安定: "Yamatonokami Yasusada",
  和泉守兼定: "Izuminokami Kanesada",
  堀川国広: "Horikawa Kunihiro",
  長曽祢虎徹: "Nagasone Kotetsu",
  蜂須賀虎徹: "Hachisuka Kotetsu",
  小狐丸: "Kogitsunemaru",
  大包平: "Okanehira",
  太閤左文字: "Taiko Samonji",
  石切丸: "Ishikirimaru",
  岩融: "Iwatooshi",
  今剣: "Imanotsurugi",
  にっかり青江: "Nikkari Aoe",
  千子村正: "Sengo Muramasa",
  蜻蛉切: "Tonbokiri",
  物吉貞宗: "Monoyoshi Sadamune",
  大倶利伽羅: "Ookurikara",
  陸奥守吉行: "Mutsunokami Yoshiyuki",
  巴形薙刀: "Tomoegata Naginata",
  明石国行: "Akashi Kuniyuki",
  鶴丸国永: "Tsurumaru Kuninaga",
  御手杵: "Otegine",
  篭手切江: "Kotegiri Gou",
  豊前江: "Buzen Gou",
  桑名江: "Kuwana Gou",
  松井江: "Matsui Gou",
  五月雨江: "Samidare Gou",
  村雲江: "Murakumo Gou",
  稲葉江: "Inaba Gou",
  日向正宗: "Hyuga Masamune",
  浦島虎徹: "Urashima Kotetsu",
  ソハヤノツルキ: "Sohayanotsurugi",
  大典太光世: "Oodenta Mitsuyo",
  水心子正秀: "Suishinshi Masahide",
  源清麿: "Minamoto Kiyomaro",
  鬼丸国綱: "Onimaru Kunitsuna",
  一期一振: "Ichigo Hitofuri",
  鯰尾藤四郎: "Namazuo Toushirou",
  骨喰藤四郎: "Honebami Toushirou",
  薬研藤四郎: "Yagen Toushirou",
  前田藤四郎: "Maeda Toushirou",
  平野藤四郎: "Hirano Toushirou",
  厚藤四郎: "Atsushi Toushirou",
  後藤藤四郎: "Gotou Toushirou",
  信濃藤四郎: "Shinano Toushirou",
  秋田藤四郎: "Akita Toushirou",
  博多藤四郎: "Hakata Toushirou",
  乱藤四郎: "Midare Toushirou",
  五虎退: "Gokotai",
  毛利藤四郎: "Mouri Toushirou",
  白山吉光: "Hakusan Yoshimitsu",
  山姥切国広: "Yamanbagiri Kunihiro",
  山姥切長義: "Yamanbagiri Chougi",
  へし切長谷部: "Heshikiri Hasebe",
  不動行光: "Fudou Yukimitsu",
  髭切: "Higekiri",
  膝丸: "Hizamaru",
  獅子王: "Shishiou",
  小烏丸: "Kogarasumaru",
  笹貫: "Sasanuki",
  後家兼光: "Goke Kanemitsu",
  大慶直胤: "Taikei Naotane",
  八丁念仏: "Hatchou Nenbutsu",
  肥前忠広: "Hizen Tadahiro",
  南海太郎朝尊: "Nankaitarou Chouson",
  大般若長光: "Daihannya Nagamitsu",
  燭台切光忠: "Shokudaikiri Mitsutada",
  福島光忠: "Fukushima Mitsutada",
  実休光忠: "Jikkyu Mitsutada",
  太鼓鐘貞宗: "Taikogane Sadamune",
  亀甲貞宗: "Kikkou Sadamune",
  千代金丸: "Chiyoganemaru",
  北谷菜切: "Chatanakiri",
  治金丸: "Chiganemaru",
  大千鳥十文字槍: "Oochidori Juumonjiyari",
  泛塵: "Hanjin",
  人間無骨: "Ningen Mukotsu",
  南泉一文字: "Nansen Ichimonji",
  山鳥毛: "Sanchoumou",
  日光一文字: "Nikko Ichimonji",
  姫鶴一文字: "Himetsuru Ichimonji",
  則宗: "Norimune",
  七星剣: "Shichiseiken",
  抜丸: "Nukemaru",
  石田正宗: "Ishida Masamune",
  京極正宗: "Kyogoku Masamune",
  孫六兼元: "Magoroku Kanemoto",
  火車切: "Kashagiri",
  九鬼正宗: "Kuki Masamune",
  雲生: "Unsho",
  太郎太刀: "Taroutachi",
  次郎太刀: "Jiroutachi",
  日本号: "Nihongou",
  同田貫正国: "Doudanuki Masakuni",
  数珠丸恒次: "Juzumaru Tsunetsugu",
  江雪左文字: "Kousetsu Samonji",
  宗三左文字: "Souza Samonji",
  小夜左文字: "Sayo Samonji",
  歌仙兼定: "Kasen Kanesada",
  鳴狐: "Nakigitsune",
  蛍丸: "Hotarumaru",
  愛染国俊: "Aizen Kunitoshi",
  静形薙刀: "Shizukagata Naginata",
  祢々切丸: "Nenekirimaru",
  白雲木: "Shirakumogi",
  富田江: "Tomita Gou",
  大野剣: "Oonoken",
  山伏国広: "Yamabushi Kunihiro",
  小竜景光: "Koryu Kagemitsu",
  古今伝授の太刀: "Kokin Denju no Tachi",
  一文字則宗: "Ichimonji Norimune",
  鶯丸: "Uguisumaru",
  地蔵行平: "Jizou Yukihira",

  // Historical figures
  徳川家康: "Tokugawa Ieyasu",
  伊達政宗: "Date Masamune",
  武蔵坊弁慶: "Musashibou Benkei",
  渡辺綱: "Watanabe no Tsuna",
  藤原泰衡: "Fujiwara no Yasuhira",
  結城秀康: "Yuki Hideyasu",
  源義経: "Minamoto no Yoshitsune",
  榎本武揚: "Enomoto Takeaki",
  足利尊氏: "Ashikaga Takauji",
  土方歳三: "Hijikata Toshizo",
  近藤勇: "Kondo Isami",
  松平信康: "Matsudaira Nobuyasu",
  天海: "Tenkai",
  勝海舟: "Katsu Kaishu",
  坂上田村麻呂: "Sakanoue no Tamuramaro",
  虎哉宗乙: "Kosai Soitsu",
  支倉常長: "Hasekura Tsunenaga",
  本阿弥光徳: "Hon'ami Kotoku",
  平将門: "Taira no Masakado",
  久坂玄瑞: "Kusaka Genzui",
  高師泰: "Ko no Moroyasu",
  沖田総司: "Okita Soji",
  松平信綱: "Matsudaira Nobutsuna",
  会沢正志斎: "Aizawa Seishisai",
  ハリス: "Townsend Harris",
  母禮: "More",
  喜多川歌麿: "Kitagawa Utamaro",
  佐々木道誉: "Sasaki Doyo",
  阿弖流為: "Aterui",
  中島登: "Nakajima Nobori",
  山田右衛門作: "Yamada Emosaku",
  永見貞愛: "Nagami Sadachika",
  井伊直弼: "Ii Naosuke",
  太田道灌: "Ota Dokan",
  蔦屋重三郎: "Tsutaya Juzaburo",
  徳川秀忠: "Tokugawa Hidetada",
  豊臣秀吉: "Toyotomi Hideyoshi",
  西郷隆盛: "Saigo Takamori",
  坂本龍馬: "Sakamoto Ryoma",
  足利直冬: "Ashikaga Tadafuyu",
  島田魁: "Shimada Kai",
  足利直義: "Ashikaga Tadayoshi",
  勝麟太郎: "Katsu Rintaro",
  高師直: "Ko no Moronao",
  弾左衛門: "Danzaemon",
  吉田松陰: "Yoshida Shoin",
  建速須佐之男命: "Takehaya Susanoo-no-Mikoto",
  厩戸皇子: "Umayado no Miko",
  三条小鍛冶宗近: "Sanjo Kokaji Munechika",
  北条政子: "Hojo Masako",
  畠山義就: "Hatakeyama Yoshinari",
  明智光秀: "Akechi Mitsuhide",
  石出帯刀吉深: "Ishide Tatewaki Yoshifuka",
  桐野利秋: "Kirino Toshiaki",
  黒田官兵衛: "Kuroda Kanbei",
  黒田孝高: "Kuroda Yoshitaka",
  黒田如水: "Kuroda Josui",
  細川ガラシャ: "Hosokawa Gracia",
  豊臣秀頼: "Toyotomi Hideyori",
  吉田東洋: "Yoshida Toyo",
  高台院: "Kodai-in",
  森蘭丸: "Mori Ranmaru",
  高山右近: "Takayama Ukon",
  大友宗麟: "Otomo Sorin",
  武市半平太: "Takechi Hanpeita",
  大村純忠: "Omura Sumitada",
  有馬晴信: "Arima Harunobu",
  足利義輝: "Ashikaga Yoshiteru",
  小西行長: "Konishi Yukinaga",
  谷三十郎: "Tani Sanjuro",
  黒田長政: "Kuroda Nagamasa",
  水野忠邦: "Mizuno Tadakuni",
  母里友信: "Mori Tomonobu",
  伊東マンショ: "Ito Mancio",
  中浦ジュリアン: "Nakaura Julian",
  鳥居耀蔵: "Torii Yozo",
  北条氏直: "Hojo Ujinao",
  永倉新八: "Nagakura Shinpachi",
  山田朝右衛門吉睦: "Yamada Asaemon Yoshimutsu",
  鎌田魚妙: "Kamata Utae",
  斎藤一: "Saito Hajime",
  藤原在吉: "Fujiwara no Ariyoshi",
  原マルティノ: "Hara Martino",
  尚寧王: "King Sho Nei",
  親鸞: "Shinran",
  窪田清音: "Kubota Sugane",

  // Sanada Ten Braves and related
  猿飛佐助: "Sarutobi Sasuke",
  穴山小助: "Anayama Kosuke",
  真田信繁: "Sanada Nobushige",
  大野治長: "Ono Harunaga",
  三好清海入道: "Miyoshi Seikai Nyudo",
  三好伊三入道: "Miyoshi Isa Nyudo",
  望月六郎: "Mochizuki Rokuro",
  霧隠才蔵: "Kirigakure Saizo",
  筧十蔵: "Kakei Juzo",
  根津甚八: "Nezu Jinpachi",
  由利鎌之助: "Yuri Kamanosuke",
  海野六郎: "Unno Rokuro",
  長尾顕長: "Nagao Akinaga",
  千々石ミゲル: "Chijiwa Miguel",

  // Tale of Genji
  光源氏: "Hikaru Genji",
  六条御息所: "Rokujo no Miyasudokoro",
  空蝉: "Utsusemi",
  末摘花: "Suetsumuhana",
  藤壺女御: "Fujitsubo no Nyogo",
  藤壺の宮: "Fujitsubo no Miya",
  葵上: "Aoi no Ue",
  小少将の君: "Koshosho no Kimi",

  // Other roles / concepts
  竹千代: "Takechiyo",
  梵天丸: "Bontenmaru",
  リョウマ: "Ryoma",
  カゲ: "Kage",
  謎の男: "Mysterious Man",
  守人: "Morito",
  阿形: "Agyo",
  吽形: "Ungyo",
  監査官: "Government Inspector",
  鵺と呼ばれる: "The Entity Called Nue",
  思五郎金: "Omoigorokane",
  母: "Mother",
  吾兵: "Gohei",
  瑣吉: "Sakichi",
  少年: "Boy",
  兄: "Brother",
  他: "Others",
  声: "Voice",
  特別協力: "Special Cooperation",
  人間キャスト: "Human Cast",
  花組芝居: "Hanagumi Shibai",
};

export const EN_PARTIAL_TERM_MAP: Array<[string, string]> = [
  ["舞台『刀剣乱舞』", "Touken Ranbu: The Stage"],
  ["ミュージカル『刀剣乱舞』", "Touken Ranbu: The Musical"],
  ["『刀剣乱舞』", '"Touken Ranbu"'],
  ["刀剣乱舞", "Touken Ranbu"],
  ["真剣乱舞祭", "Shinken Ranbu Festival"],
  ["歌合 乱舞狂乱", "Uta-awase Ranbu Kyouran"],
  ["壽 乱舞音曲祭", "Kotobuki Ranbu Ongyokusai"],
  ["単独行", "Solo Performance"],
  ["阿津賀志山異聞", "Atsukashiyama Ibun"],
  ["幕末天狼傳", "Bakumatsu Tenro Den"],
  ["三百年の子守唄", "Three Hundred Years' Lullaby"],
  ["つはものどもがゆめのあと", "Tsuwamonodomo ga Yume no Ato"],
  ["結びの響、始まりの音", "The Sound of Ties, The First Note"],
];

export const translateExactTermEn = (value?: string | null) => {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  return EN_EXACT_TERM_MAP[raw] ?? raw;
};

export const translateKnownTermsEn = (value?: string | null) => {
  const raw = String(value ?? "").trim();
  if (!raw) return "";

  if (EN_EXACT_TERM_MAP[raw]) return EN_EXACT_TERM_MAP[raw];

  let next = raw;
  for (const [source, target] of EN_PARTIAL_TERM_MAP) {
    next = next.replaceAll(source, target);
  }
  return next;
};
