// Touken Ranbu-first English fallback dictionary.
// We keep this lightweight on purpose so we can expand it as more series are translated.

export const EN_EXACT_TERM_MAP: Record<string, string> = {
  // Companies / orgs
  ネルケプランニング: "Nelke Planning",
  マーベラスエンターテイメント: "Marvelous Entertainment",
  マーベラス: "Marvelous",
  ニトロプラス: "Nitroplus",
  東宝: "TOHO",
  "DMM GAMES": "DMM GAMES",
  "NITRO PLUS": "NITRO PLUS",
  山田和也: "Kazuya Yamada",
  藤沢文翁: "Bun-O Fujisawa",
  笠浦静花: "Shizuka Kasaura",
  帝国劇場: "Imperial Theatre",
  梅田芸術劇場メインホール: "Umeda Arts Theater Main Hall",
  博多座: "Hakataza Theater",
  "東京建物 Brillia HALL": "Tokyo Tatemono Brillia HALL",
  信: "Shin",
  嬴政: "Ei Sei",
  漂: "Hyou",
  河了貂: "Ka Ryo Ten",
  楊端和: "Yo Tanwa",
  壁: "Heki",
  成蟜: "Seikyo",
  左慈: "Saji",
  バジオウ: "Bajio",
  紫夏: "Shika",
  昌文君: "Shoubunkun",
  王騎: "Ouki",
  東京ベイNKホール: "Tokyo Bay NK Hall",
  青春学園: "Seigaku",
  不動峰: "Fudomine",
  聖ルドルフ学院: "St. Rudolph",
  山吹中: "Yamabuki",
  氷帝学園: "Hyotei",
  玉林中: "Tama Junior High",
  特別出演: "Special Appearance",
  六角中: "Rokkaku",
  立海大附属中: "Rikkai",
  比嘉中: "Higa",
  四天宝寺中: "Shitenhoji",
  "U-17": "U-17",
  日替わりゲスト: "Rotating Guest",
  友情出演: "Special Guest Appearance",
  "U-17コーチ": "U-17 Coaches",
  越前リョーマ: "Ryoma Echizen",
  手塚国光: "Kunimitsu Tezuka",
  大石秀一郎: "Shuichiro Oishi",
  不二周助: "Shusuke Fuji",
  菊丸英二: "Eiji Kikumaru",
  乾貞治: "Sadaharu Inui",
  河村隆: "Takashi Kawamura",
  桃城武: "Takeshi Momoshiro",
  海堂薫: "Kaoru Kaido",
  堀尾聡史: "Satoshi Horio",
  加藤勝郎: "Katsuro Kato",
  水野カツオ: "Katsuo Mizuno",
  荒井将史: "Masashi Arai",
  池田雅也: "Masaya Ikeda",
  林大介: "Daisuke Hayashi",
  橘桔平: "Kippei Tachibana",
  伊武深司: "Shinji Ibu",
  神尾アキラ: "Akira Kamio",
  石田鉄: "Tetsu Ishida",
  桜井雅也: "Masaya Sakurai",
  観月はじめ: "Hajime Mizuki",
  赤澤吉朗: "Yoshiro Akazawa",
  不二裕太: "Yuta Fuji",
  木更津淳: "Atsushi Kisarazu",
  柳沢慎也: "Shinya Yanagisawa",
  金田一郎: "Ichiro Kaneda",
  千石清純: "Kiyosumi Sengoku",
  亜久津仁: "Jin Akutsu",
  南健太郎: "Kentaro Minami",
  東方雅美: "Masami Higashikata",
  壇太一: "Taichi Dan",
  室町十次: "Juji Muromachi",
  跡部景吾: "Keigo Atobe",
  忍足侑士: "Yuushi Oshitari",
  向日岳人: "Gakuto Mukahi",
  宍戸亮: "Ryo Shishido",
  芥川慈郎: "Jiro Akutagawa",
  樺地崇弘: "Takahiro Kabaji",
  鳳長太郎: "Chotaro Ohtori",
  日吉若: "Wakashi Hiyoshi",
  泉智也: "Tomoya Izumi",
  布川公義: "Kimitoshi Nunokawa",
  越前南次郎: "Nanjiro Echizen",
  佐々部順一: "Junichi Sasabe",
  葵剣太郎: "Kentaro Aoi",
  佐伯虎次郎: "Kojiro Saeki",
  黒羽春風: "Harukaze Kurobane",
  天根ヒカル: "Hikaru Amane",
  木更津亮: "Ryo Kisarazu",
  首藤聡: "Satoshi Shudou",
  幸村精市: "Seiichi Yukimura",
  真田弦一郎: "Genichiro Sanada",
  柳蓮二: "Renji Yanagi",
  仁王雅治: "Masaharu Niou",
  柳生比呂士: "Hiroshi Yagyu",
  丸井ブン太: "Bunta Marui",
  ジャッカル桑原: "Jackal Kuwahara",
  切原赤也: "Akaya Kirihara",
  木手永四郎: "Eishiro Kite",
  甲斐裕次郎: "Yujiro Kai",
  平古場凛: "Rin Hirakoba",
  知念寛: "Hiroshi Chinen",
  田仁志慧: "Kei Tanishi",
  不知火知弥: "Tomoya Shiranuhi",
  新垣浩一: "Koichi Aragaki",
  白石蔵ノ介: "Kuranosuke Shiraishi",
  千歳千里: "Senri Chitose",
  金色小春: "Koharu Konjiki",
  一氏ユウジ: "Yuuji Oshitari",
  忍足謙也: "Kenya Oshitari",
  石田銀: "Gin Ishida",
  財前光: "Hikaru Zaizen",
  遠山金太郎: "Kintaro Toyama",
  平等院鳳凰: "Byodo-in Houou",
  種ヶ島修二: "Shuji Tanegashima",
  デューク渡邊: "Duke Watanabe",
  徳川カズヤ: "Kazuya Tokugawa",
  鬼十次郎: "Jujiro Oni",
  入江奏多: "Kanata Irie",
  大曲竜次: "Ryuji Oomagari",
  君島育斗: "Ikuto Kimijima",
  遠野篤京: "Atsukyou Toono",
  越知月光: "Gekkou Ochi",
  毛利寿三郎: "Jusaburo Mouri",
  中河内外道: "Gedou Nakagawachi",
  大和祐大: "Yuudai Yamato",
  都忍: "Shinobu Miyako",
  松平親彦: "Chikahiko Matsudaira",
  鈴木惷: "Shun Suzuki",
  鷲尾一茶: "Issa Washio",
  黒部由起夫: "Yukio Kurobe",
  齋藤至: "Itaru Saito",
  三船入道: "Nyudo Mifune",
  "ユークリッド・エージェンシー": "Euclid Agency",

  // Common labels / concepts
  刀剣乱舞: "Touken Ranbu",
  刀ステ: "Touken Ranbu: The Stage",
  刀ミュ: "Touken Ranbu: The Musical",
  真剣乱舞祭: "Shinken Ranbu Festival",
  単独行: "Solo Performance",
  日替わり出演: "Rotating appearance",
  会場替わり出演: "Venue-specific appearance",
  のみ出演: "Appears only in selected performances",
  複数役: "Multiple roles",
  再登場: "Returning appearance",
  刀剣男士: "Touken Danshi",
  審神者: "Saniwa",
  本丸: "Honmaru",
  時間遡行軍: "History Retrograde Army",
  歴史修正主義者: "Historical Revisionists",
  検非違使: "Kebiishi",
  歴史上人物: "Historical Figures",
  その他: "Others",
  新選組: "Shinsengumi",
  真田十勇士: "Sanada Ten Braves",
  源氏: "Minamoto Clan",
  平氏: "Taira Clan",
  奥州藤原氏: "Oshu Fujiwara Clan",
  織田軍: "Oda Army",
  伊達軍: "Date Army",
  幕府軍: "Shogunate Army",
  新政府軍: "New Government Army",
  講談師: "Storyteller",
  源氏物語: "The Tale of Genji",
  アンサンブル: "Ensemble",
  ダンサー: "Dancers",
  映像出演: "Video Appearance",
  声の出演: "Voice Appearance",
  原案: "Original Work",
  原作: "Original Work",
  脚本: "Script",
  演出: "Direction",
  音楽: "Music",
  作詞: "Lyrics",
  アクション監督: "Action Director",
  ディレクター: "Director",
  コピーライト: "Copyright",
  総監修: "Chief Supervisor",
  制作: "Production",
  配給: "Distribution",
  振付: "Choreography",
  ステージソング: "Stage Song",
  製作: "Production",
  音楽監督: "Music Direction",
  主催: "Organizer",
  "47都道府県": "All 47 Prefectures",
  東京凱旋: "Tokyo Return Engagement",
  中国: "China",
  パリ: "Paris",
  台湾: "Taiwan",
  マレーシア: "Malaysia",
  北海道: "Hokkaido",
  青森: "Aomori",
  岩手: "Iwate",
  宮城: "Miyagi",
  秋田: "Akita",
  山形: "Yamagata",
  福島: "Fukushima",
  茨城: "Ibaraki",
  栃木: "Tochigi",
  群馬: "Gunma",
  埼玉: "Saitama",
  千葉: "Chiba",
  東京: "Tokyo",
  神奈川: "Kanagawa",
  新潟: "Niigata",
  富山: "Toyama",
  石川: "Ishikawa",
  福井: "Fukui",
  山梨: "Yamanashi",
  長野: "Nagano",
  岐阜: "Gifu",
  静岡: "Shizuoka",
  愛知: "Aichi",
  三重: "Mie",
  滋賀: "Shiga",
  京都: "Kyoto",
  大阪: "Osaka",
  兵庫: "Hyogo",
  奈良: "Nara",
  和歌山: "Wakayama",
  鳥取: "Tottori",
  島根: "Shimane",
  岡山: "Okayama",
  広島: "Hiroshima",
  山口: "Yamaguchi",
  徳島: "Tokushima",
  香川: "Kagawa",
  愛媛: "Ehime",
  高知: "Kochi",
  福岡: "Fukuoka",
  佐賀: "Saga",
  長崎: "Nagasaki",
  熊本: "Kumamoto",
  大分: "Oita",
  宮崎: "Miyazaki",
  鹿児島: "Kagoshima",
  沖縄: "Okinawa",
  札幌: "Sapporo",
  仙台: "Sendai",
  横浜: "Yokohama",
  名古屋: "Nagoya",
  神戸: "Kobe",
  北九州: "Kitakyushu",
  "TOKYO DOME CITY HALL": "TOKYO DOME CITY HALL",
  "TOKYO DOME CITY HALL（TDCホール）": "TOKYO DOME CITY HALL (TDC Hall)",
  "TDCホール": "TDC Hall",
  日本青年館: "Nippon Seinenkan",
  日本青年館ホール: "Nippon Seinenkan Hall",
  "日本青年館 大ホール": "Nippon Seinenkan Main Hall",
  明治座: "Meijiza Theater",
  東京メルパルクホール: "Mielparque Hall Tokyo",
  "東京芸術劇場 中ホール": "Tokyo Metropolitan Theatre Playhouse",
  "東京建物 Brillia HALL 箕面": "Tokyo Tatemono Brillia HALL Minoh",
  "東京建物 Brillia HALL 箕面 大ホール": "Tokyo Tatemono Brillia HALL Minoh Main Hall",
  "天王洲 銀河劇場": "Galaxy Theatre",
  "品川プリンスホテル ステラボール": "Shinagawa Prince Hotel Stellar Ball",
  "アイーア 2.5 シアター トーキョー": "AiiA 2.5 Theater Tokyo",
  "アイーア 2.5 シアター トーキョー（AiiA 2.5 Theater Tokyo ※現在は閉館していますが、過去作の登録には必須です）":
    "AiiA 2.5 Theater Tokyo",
  "AiiA 2.5 Theater Tokyo": "AiiA 2.5 Theater Tokyo",
  "EX THEATER ROPPONGI": "EX THEATER ROPPONGI",
  "国立代々木競技場 第一体育館": "Yoyogi National Gymnasium First Gymnasium",
  "武蔵野の森総合スポーツプラザ メインアリーナ": "Musashino Forest Sport Plaza Main Arena",
  有明アリーナ: "Ariake Arena",
  東京ガーデンシアター: "Tokyo Garden Theater",
  豊洲PIT: "Toyosu PIT",
  オリックス劇場: "ORIX Theater",
  大阪メルパルクホール: "Mielparque Hall Osaka",
  メルパルクホール大阪: "Mielparque Hall Osaka",
  "梅田芸術劇場 メインホール": "Umeda Arts Theater Main Hall",
  "梅田芸術劇場 シアター・ドラマシティ": "Umeda Arts Theater Drama City",
  森ノ宮ピロティホール: "Morinomiya Piloti Hall",
  大阪城ホール: "Osaka-jo Hall",
  あべのHoop: "Abeno Hoop",
  "COOL JAPAN PARK OSAKA WWホール": "COOL JAPAN PARK OSAKA WW Hall",
  "COOL JAPAN PARK OSAKA TTホール": "COOL JAPAN PARK OSAKA TT Hall",
  "COOL JAPAN PARK OSAKA WWホール / TTホール": "COOL JAPAN PARK OSAKA WW Hall / TT Hall",
  "名古屋国際会議場 センチュリーホール": "Nagoya Congress Center Century Hall",
  "愛知県芸術劇場 大ホール": "Aichi Prefectural Art Theater Grand Hall",
  御園座: "Misonoza",
  名鉄ホール: "Meitetsu Hall",
  日本ガイシホール: "Nippon Gaishi Hall",
  "刈谷市総合文化センター アイリス 大ホール": "Kariya City Cultural Center Iris Grand Hall",
  "福岡サンパレス ホテル＆ホール": "Fukuoka Sunpalace Hotel & Hall",
  "福岡サンパレス ホテル&ホール": "Fukuoka Sunpalace Hotel & Hall",
  北九州ソレイユホール: "Kitakyushu Soleil Hall",
  "アルモニーサンク 北九州ソレイユホール": "Harmony Cinq Kitakyushu Soleil Hall",
  マリンメッセ福岡: "Marine Messe Fukuoka",
  "久留米シティプラザ・グランドホール": "Kurume City Plaza Grand Hall",
  仙台サンプラザホール: "Sendai Sunplaza Hall",
  "多賀城市民会館 大ホール": "Tagajo Civic Hall Main Hall",
  "多賀城市文化センター": "Tagajo Cultural Center",
  "広島文化学園HBGホール": "Hiroshima Bunka Gakuen HBG Hall",
  "広島グリーンアリーナ": "Hiroshima Green Arena",
  京都劇場: "Kyoto Theater",
  "香川県県民ホール アクトホール": "Kagawa Prefectural Hall Act Hall",
  神戸ワールド記念ホール: "Kobe World Memorial Hall",
  新歌舞伎座: "Shinkabukiza Theater",
  "IHIステージアラウンド東京": "IHI Stage Around Tokyo",
  "幕張メッセ 幕張イベントホール": "Makuhari Messe Makuhari Event Hall",
  シアター1010: "Theatre 1010",
  "パルテノン多摩 大ホール": "Parthenon Tama Main Hall",
  "SkyシアターMBS": "Sky Theater MBS",
  "箕面市立文化芸能劇場 大ホール": "Minoh City Cultural and Performing Arts Theater Main Hall",
  "真駒内セキスイハイムアイスアリーナ": "Makomanai Sekisui Heim Ice Arena",
  "サンドーム福井": "Sundome Fukui",
  "富士急ハイランド・コニファーフォレスト": "Fuji-Q Highland Conifer Forest",
  "サンケイホールブリーゼ": "Sankei Hall Breeze",
  "アイプラザ豊橋": "Ai Plaza Toyohashi",
  "熊本城ホール": "Kumamoto-jo Hall",
  "全国47都道府県の各会場": "Venues across all 47 prefectures nationwide",
  "あましんアルカイックホール": "Amashin Archaic Hall",
  "舞浜アンフィシアター": "Maihama Amphitheater",
  "市民会館シアーズホーム夢ホール": "Shimin Kaikan Sears Home Yume Hall",
  "長野ビッグハット": "Nagano Big Hat",
  "宮城・セキスイハイムスーパーアリーナ": "Miyagi Sekisui Heim Super Arena",
  "北海きたえーる": "Hokkai Kitayell",
  "国立台湾大学総合体育館": "National Taiwan University Sports Center",
  "National Taiwan University Sports Center": "National Taiwan University Sports Center",
  "サイアム・パラゴン・ホール": "Siam Paragon Hall",
  "Siam Paragon Hall": "Siam Paragon Hall",
  "パレ・デ・コングレ・ド・パリ": "Palais des congrès de Paris",
  "Palais des congrès de Paris": "Palais des congrès de Paris",
  "虹橋芸術センター": "Hongqiao Art Center",
  "Hongqiao Art Center": "Hongqiao Art Center",

  // Sword warriors / role names
  加州清光: "Kashu Kiyomitsu",
  三日月宗近: "Mikazuki Munechika",
  大和守安定: "Yamatonokami Yasusada",
  和泉守兼定: "Izuminokami Kanesada",
  堀川国広: "Horikawa Kunihiro",
  長曽祢虎徹: "Nagasone Kotetsu",
  蜂須賀虎徹: "Hachisuka Kotetsu",
  小狐丸: "Kogitsunemaru",
  大包平: "Okanehira",
  太閤左文字: "Taiko Samonji",
  石切丸: "Ishikirimaru",
  岩融: "Iwatooshi",
  今剣: "Imanotsurugi",
  にっかり青江: "Nikkari Aoe",
  千子村正: "Sengo Muramasa",
  蜻蛉切: "Tonbokiri",
  物吉貞宗: "Monoyoshi Sadamune",
  大倶利伽羅: "Ookurikara",
  陸奥守吉行: "Mutsunokami Yoshiyuki",
  巴形薙刀: "Tomoegata Naginata",
  明石国行: "Akashi Kuniyuki",
  鶴丸国永: "Tsurumaru Kuninaga",
  御手杵: "Otegine",
  篭手切江: "Kotegiri Gou",
  豊前江: "Buzen Gou",
  桑名江: "Kuwana Gou",
  松井江: "Matsui Gou",
  五月雨江: "Samidare Gou",
  村雲江: "Murakumo Gou",
  稲葉江: "Inaba Gou",
  日向正宗: "Hyuga Masamune",
  浦島虎徹: "Urashima Kotetsu",
  ソハヤノツルキ: "Sohayanotsurugi",
  大典太光世: "Oodenta Mitsuyo",
  水心子正秀: "Suishinshi Masahide",
  源清麿: "Minamoto Kiyomaro",
  鬼丸国綱: "Onimaru Kunitsuna",
  一期一振: "Ichigo Hitofuri",
  鯰尾藤四郎: "Namazuo Toushirou",
  骨喰藤四郎: "Honebami Toushirou",
  薬研藤四郎: "Yagen Toushirou",
  前田藤四郎: "Maeda Toushirou",
  平野藤四郎: "Hirano Toushirou",
  厚藤四郎: "Atsushi Toushirou",
  後藤藤四郎: "Gotou Toushirou",
  信濃藤四郎: "Shinano Toushirou",
  秋田藤四郎: "Akita Toushirou",
  博多藤四郎: "Hakata Toushirou",
  乱藤四郎: "Midare Toushirou",
  五虎退: "Gokotai",
  毛利藤四郎: "Mouri Toushirou",
  白山吉光: "Hakusan Yoshimitsu",
  山姥切国広: "Yamanbagiri Kunihiro",
  山姥切長義: "Yamanbagiri Chougi",
  へし切長谷部: "Heshikiri Hasebe",
  不動行光: "Fudou Yukimitsu",
  髭切: "Higekiri",
  膝丸: "Hizamaru",
  獅子王: "Shishiou",
  小烏丸: "Kogarasumaru",
  笹貫: "Sasanuki",
  後家兼光: "Goke Kanemitsu",
  大慶直胤: "Taikei Naotane",
  八丁念仏: "Hatchou Nenbutsu",
  肥前忠広: "Hizen Tadahiro",
  南海太郎朝尊: "Nankaitarou Chouson",
  大般若長光: "Daihannya Nagamitsu",
  燭台切光忠: "Shokudaikiri Mitsutada",
  福島光忠: "Fukushima Mitsutada",
  実休光忠: "Jikkyu Mitsutada",
  太鼓鐘貞宗: "Taikogane Sadamune",
  亀甲貞宗: "Kikkou Sadamune",
  千代金丸: "Chiyoganemaru",
  北谷菜切: "Chatanakiri",
  治金丸: "Chiganemaru",
  大千鳥十文字槍: "Oochidori Juumonjiyari",
  泛塵: "Hanjin",
  人間無骨: "Ningen Mukotsu",
  南泉一文字: "Nansen Ichimonji",
  山鳥毛: "Sanchoumou",
  日光一文字: "Nikko Ichimonji",
  姫鶴一文字: "Himetsuru Ichimonji",
  則宗: "Norimune",
  七星剣: "Shichiseiken",
  抜丸: "Nukemaru",
  石田正宗: "Ishida Masamune",
  京極正宗: "Kyogoku Masamune",
  孫六兼元: "Magoroku Kanemoto",
  火車切: "Kashagiri",
  九鬼正宗: "Kuki Masamune",
  雲生: "Unsho",
  太郎太刀: "Taroutachi",
  次郎太刀: "Jiroutachi",
  日本号: "Nihongou",
  同田貫正国: "Doudanuki Masakuni",
  数珠丸恒次: "Juzumaru Tsunetsugu",
  江雪左文字: "Kousetsu Samonji",
  宗三左文字: "Souza Samonji",
  小夜左文字: "Sayo Samonji",
  歌仙兼定: "Kasen Kanesada",
  鳴狐: "Nakigitsune",
  蛍丸: "Hotarumaru",
  愛染国俊: "Aizen Kunitoshi",
  静形薙刀: "Shizukagata Naginata",
  祢々切丸: "Nenekirimaru",
  白雲木: "Shirakumogi",
  富田江: "Tomita Gou",
  大野剣: "Oonoken",
  山伏国広: "Yamabushi Kunihiro",
  小竜景光: "Koryu Kagemitsu",
  古今伝授の太刀: "Kokin Denju no Tachi",
  一文字則宗: "Ichimonji Norimune",
  鶯丸: "Uguisumaru",
  地蔵行平: "Jizou Yukihira",

  // Historical figures
  徳川家康: "Tokugawa Ieyasu",
  伊達政宗: "Date Masamune",
  岡田以蔵: "Okada Izo",
  武蔵坊弁慶: "Musashibou Benkei",
  渡辺綱: "Watanabe no Tsuna",
  藤原泰衡: "Fujiwara no Yasuhira",
  結城秀康: "Yuki Hideyasu",
  源義経: "Minamoto no Yoshitsune",
  源頼朝: "Minamoto no Yoritomo",
  源頼光: "Minamoto no Raiko",
  榎本武揚: "Enomoto Takeaki",
  足利尊氏: "Ashikaga Takauji",
  土方歳三: "Hijikata Toshizo",
  近藤勇: "Kondo Isami",
  "近藤 勇": "Kondo Isami",
  松平信康: "Matsudaira Nobuyasu",
  天海: "Tenkai",
  勝海舟: "Katsu Kaishu",
  勝林太郎: "Katsu Rintaro",
  "勝 林太郎": "Katsu Rintaro",
  "勝 麟太郎": "Katsu Rintaro",
  麟太郎: "Rintaro",
  坂上田村麻呂: "Sakanoue no Tamuramaro",
  虎哉宗乙: "Kosai Soitsu",
  支倉常長: "Hasekura Tsunenaga",
  本阿弥光徳: "Hon'ami Kotoku",
  平将門: "Taira no Masakado",
  久坂玄瑞: "Kusaka Genzui",
  高師泰: "Ko no Moroyasu",
  沖田総司: "Okita Soji",
  松平信綱: "Matsudaira Nobutsuna",
  会沢正志斎: "Aizawa Seishisai",
  ハリス: "Townsend Harris",
  母禮: "More",
  喜多川歌麿: "Kitagawa Utamaro",
  佐々木道誉: "Sasaki Doyo",
  阿弖流為: "Aterui",
  中島登: "Nakajima Nobori",
  山田右衛門作: "Yamada Emosaku",
  永見貞愛: "Nagami Sadachika",
  井伊直弼: "Ii Naosuke",
  太田道灌: "Ota Dokan",
  蔦屋重三郎: "Tsutaya Juzaburo",
  徳川秀忠: "Tokugawa Hidetada",
  豊臣秀吉: "Toyotomi Hideyoshi",
  西郷隆盛: "Saigo Takamori",
  坂本龍馬: "Sakamoto Ryoma",
  足利直冬: "Ashikaga Tadafuyu",
  島田魁: "Shimada Kai",
  足利直義: "Ashikaga Tadayoshi",
  勝麟太郎: "Katsu Rintaro",
  高師直: "Ko no Moronao",
  弾左衛門: "Danzaemon",
  吉田松陰: "Yoshida Shoin",
  建速須佐之男命: "Takehaya Susanoo-no-Mikoto",
  厩戸皇子: "Umayado no Miko",
  三条小鍛冶宗近: "Sanjo Kokaji Munechika",
  北条政子: "Hojo Masako",
  畠山義就: "Hatakeyama Yoshinari",
  明智光秀: "Akechi Mitsuhide",
  石出帯刀吉深: "Ishide Tatewaki Yoshifuka",
  桐野利秋: "Kirino Toshiaki",
  黒田官兵衛: "Kuroda Kanbei",
  黒田孝高: "Kuroda Yoshitaka",
  黒田如水: "Kuroda Josui",
  細川ガラシャ: "Hosokawa Gracia",
  豊臣秀頼: "Toyotomi Hideyori",
  吉田東洋: "Yoshida Toyo",
  高台院: "Kodai-in",
  森蘭丸: "Mori Ranmaru",
  細川忠興: "Hosokawa Tadaoki",
  高山右近: "Takayama Ukon",
  大友宗麟: "Otomo Sorin",
  武市半平太: "Takechi Hanpeita",
  大村純忠: "Omura Sumitada",
  有馬晴信: "Arima Harunobu",
  足利義輝: "Ashikaga Yoshiteru",
  小西行長: "Konishi Yukinaga",
  谷三十郎: "Tani Sanjuro",
  "谷 三十郎": "Tani Sanjuro",
  黒田長政: "Kuroda Nagamasa",
  水野忠邦: "Mizuno Tadakuni",
  母里友信: "Mori Tomonobu",
  伊東マンショ: "Ito Mancio",
  中浦ジュリアン: "Nakaura Julian",
  鳥居耀蔵: "Torii Yozo",
  北条氏直: "Hojo Ujinao",
  永倉新八: "Nagakura Shinpachi",
  山南敬助: "Yamanami Keisuke",
  山田朝右衛門吉睦: "Yamada Asaemon Yoshimutsu",
  鎌田魚妙: "Kamata Utae",
  斎藤一: "Saito Hajime",
  "斎藤 一": "Saito Hajime",
  藤原在吉: "Fujiwara no Ariyoshi",
  原マルティノ: "Hara Martino",
  尚寧王: "King Sho Nei",
  親鸞: "Shinran",
  窪田清音: "Kubota Sugane",
  弥助: "Yasuke",
  片倉景綱: "Katakura Kagetsuna",

  // Sanada Ten Braves and related
  猿飛佐助: "Sarutobi Sasuke",
  穴山小助: "Anayama Kosuke",
  真田信繁: "Sanada Nobushige",
  大野治長: "Ono Harunaga",
  三好清海入道: "Miyoshi Seikai Nyudo",
  三好伊三入道: "Miyoshi Isa Nyudo",
  望月六郎: "Mochizuki Rokuro",
  霧隠才蔵: "Kirigakure Saizo",
  筧十蔵: "Kakei Juzo",
  "筧 十蔵": "Kakei Juzo",
  根津甚八: "Nezu Jinpachi",
  由利鎌之助: "Yuri Kamanosuke",
  海野六郎: "Unno Rokuro",
  長尾顕長: "Nagao Akinaga",
  千々石ミゲル: "Chijiwa Miguel",

  // Tale of Genji
  光源氏: "Hikaru Genji",
  六条御息所: "Rokujo no Miyasudokoro",
  空蝉: "Utsusemi",
  末摘花: "Suetsumuhana",
  藤壺女御: "Fujitsubo no Nyogo",
  藤壺の宮: "Fujitsubo no Miya",
  葵上: "Aoi no Ue",
  小少将の君: "Koshosho no Kimi",

  // Other roles / concepts
  竹千代: "Takechiyo",
  梵天丸: "Bontenmaru",
  リョウマ: "Ryoma",
  少年リョウマ: "Young Ryoma",
  カゲ: "Kage",
  謎の男: "Mysterious Man",
  守人: "Morito",
  阿形: "Agyo",
  吽形: "Ungyo",
  監査官: "Government Inspector",
  鵺と呼ばれる: "The Entity Called Nue",
  思五郎金: "Omoigorokane",
  母: "Mother",
  吾兵: "Gohei",
  瑣吉: "Sakichi",
  少年: "Boy",
  兄: "Brother",
  弟: "Younger Brother",
  他: "Others",
  声: "Voice",
  特別協力: "Special Cooperation",
  人間キャスト: "Human Cast",
  花組芝居: "Hanagumi Shibai",

  // Writers / directors / choreographers
  茅野イサム: "Isamu Kayano",
  末満健一: "Kenichi Suemitsu",
  上島雪夫: "Yukio Ueshima",
  浅井さやか: "Sayaka Asai",
  御笠ノ忠次: "Chuji Mikasano",
  三ツ矢雄二: "Yuji Mitsuya",
  西田シャトナー: "Shatner Nishida",
  西田大輔: "Daisuke Nishida",
  毛利亘宏: "Nobuhiro Mouri",
  吉谷晃太朗: "Kotaro Yoshitani",
  松崎史也: "Fumiya Matsuzaki",
  伊藤マサミ: "Masami Ito",
  植木豪: "Go Ueki",
  児玉明子: "Akiko Kodama",
  三浦香: "Kaori Miura",
  元吉庸泰: "Tsuneyasu Motoyoshi",
  伊勢直弘: "Naohiro Ise",
  川尻恵太: "Keita Kawajiri",
  中屋敷法仁: "Norihito Nakayashiki",
  ほさかよう: "Yo Hosaka",
  なるせゆうせい: "Yusei Naruse",
  赤澤ムック: "Mook Akazawa",
  亀田真二郎: "Shinjiro Kameda",
  石丸さち子: "Sachiko Ishimaru",
  荻田浩一: "Koichi Ogita",
  許斐剛: "Takeshi Konomi",
  佐橋俊彦: "Toshihiko Sahashi",
};

export const EN_PARTIAL_TERM_MAP: Array<[string, string]> = [
  ["「刀剣乱舞ONLINE」より", 'From "Touken Ranbu ONLINE"'],
  ["刀剣乱舞ONLINE", "Touken Ranbu ONLINE"],
  ["「キングダム」原泰久", '"Kingdom" by Yasuhisa Hara'],
  ["（集英社「週刊ヤングジャンプ」連載）", '(serialized in Shueisha\'s Weekly Young Jump)'],
  ['(集英社「週刊ヤングジャンプ」連載)', '(serialized in Shueisha\'s Weekly Young Jump)'],
  ['「キングダム」原泰久（集英社「週刊ヤングジャンプ」連載）', '"Kingdom" by Yasuhisa Hara (serialized in Shueisha\'s Weekly Young Jump)'],
  ["札幌文化芸術劇場hitaru", "Sapporo Cultural Arts Theater hitaru"],
  ["帝国劇場 / 梅田芸術劇場メインホール / 博多座 / 札幌文化芸術劇場hitaru", "Imperial Theatre / Umeda Arts Theater Main Hall / Hakataza Theater / Sapporo Cultural Arts Theater hitaru"],
  ["東京公演のみ", "Tokyo performances only"],
  ["大阪・福岡公演のみ", "Osaka and Fukuoka performances only"],
  ["※東京公演のみ", "※Tokyo performances only"],
  ["※大阪・福岡公演のみ", "※Osaka and Fukuoka performances only"],
  ['許斐剛「テニスの王子様」(集英社 ジャンプ コミックス刊)', 'Takeshi Konomi, "The Prince of Tennis" (Shueisha Jump Comics)'],
  ["マーベラスエンターテイメント/ネルケプランニング", "Marvelous Entertainment / Nelke Planning"],
  ["原作 :", "Original Work:"],
  ["原作:", "Original Work:"],
  ["舞台『刀剣乱舞』", "Touken Ranbu: The Stage"],
  ["ミュージカル『刀剣乱舞』", "Touken Ranbu: The Musical"],
  ["『刀剣乱舞』", '"Touken Ranbu"'],
  ["刀剣乱舞", "Touken Ranbu"],
  ["真剣乱舞祭", "Shinken Ranbu Festival"],
  ["歌合 乱舞狂乱", "Uta-awase Ranbu Kyouran"],
  ["壽 乱舞音曲祭", "Kotobuki Ranbu Ongyokusai"],
  ["単独行", "Solo Performance"],
  ["阿津賀志山異聞", "Atsukashiyama Ibun"],
  ["幕末天狼傳", "Bakumatsu Tenro Den"],
  ["三百年の子守唄", "Three Hundred Years' Lullaby"],
  ["つはものどもがゆめのあと", "Tsuwamonodomo ga Yume no Ato"],
  ["結びの響、始まりの音", "The Sound of Ties, The First Note"],
];

export const translateExactTermEn = (value?: string | null) => {
  const raw = String(value ?? "").trim();
  if (!raw) return "";
  return EN_EXACT_TERM_MAP[raw] ?? raw;
};

export const translateKnownTermsEn = (value?: string | null) => {
  const raw = String(value ?? "").trim();
  if (!raw) return "";

  if (EN_EXACT_TERM_MAP[raw]) return EN_EXACT_TERM_MAP[raw];

  let next = raw;
  for (const [source, target] of EN_PARTIAL_TERM_MAP) {
    next = next.replaceAll(source, target);
  }
  return next;
};
